### PR TITLE
Add software watchdog support in pipe-demo

### PR DESCRIPTION
**Pull request by sudipm-mukherjee**

### CODE REVIEW

**Comment by AGLExport** [comment]
Thank you sudipm

This patch depend to bsp, that is my understanding.

My opinion "modprobe softdog" should move into the bsp layer recipe.  On the other hand, currently meta-elisa only to use qemu and bsp layer design was not discuss.

I propose to step of work
1) This patch merge into meta-elisa.
2) Start discussion for bsp layer design.
3) Update to the design.

How do you think?

**Comment by sudipm-mukherjee** [comment]
> Thank you sudipm
> 
> This patch depend to bsp, that is my understanding.
> 
> My opinion "modprobe softdog" should move into the bsp layer recipe. On the other hand, currently meta-elisa only to use qemu and bsp layer design was not discuss.

Loading a module should not be BSP. imho, BSP should only have changes for the kernel or any lower level libraries but should not have service files changes for loading a module. This module is only needed if this service file is used and there is no need to load it if the service file is removed in the future. If we integrate any kernel patches for watchdog then that definitely should be in BSP.

**Comment by AGLExport** [comment]
Whether built-in driver or dynamically loading driver is depend on the kernel configuration.

The typical bsp layer is including board specific userland setting. 
For example this udev configuration recipe is including bsp layer. 
https://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/tree/recipes-connectivity/pi-bluetooth/pi-bluetooth_0.1.12.bb
My understanding, this modprobe is a same situations. 

meta-elisa has a directory for the bsp layer.
meta-elisa/bsp/meta-elisa-bsp-qemu/
But it can't use.  This issue is to be discuss in step 2.

**Comment by AGLExport** [comment]
At 1st step.  This patch merge into meta-elisa.

**Comment by dl9pf** [comment]
I see you add modprobe softdog.

This means you need to ensure: CONFIG_SOFT_WATCHDOG=m 

That needs to happen in every kernel, but here is no global 'kernel.bbappend' to do that in 'every' kernel. 
For AGL we have 
meta-agl/meta-agl-core/recipes-kernel/linux/linux-agl.inc   that we inject into the BSP's kernels via our own bbappend to them (e.g. linux-raspberrypi_%.bbappend). So there (linux-agl.inc) you could add the requirement for CONFIG_SOFT_WATCHDOG=m .

As a minimum requirement we could RDEPEND_${PN} += "kernel-module-softdog"   as this will bark when there is no softdog module available in the kernel.

**Comment by sudipm-mukherjee** [comment]
> CONFIG_SOFT_WATCHDOG

Thanks @dl9pf.
Or maybe we can add a config in meta-elisa to enable CONFIG_SOFT_WATCHDOG. But then I think that needs to go to BSP layer.
I will add the `RDEPEND` on  the next pull request changing the repo link.

**Pull request merged**
