### PR TITLE
Request pull to add i6300 watchdog support to the ELISA demo

### PR DESCRIPTION
**Pull request by cminyard**
We had a system fail for the work I was doing, so I had some time to work on this.  I have two patches:

Add the bsp directory to the BBLAYERS.

Switch over to the i6300 watchdog.

A few notes:

If you just pull and rebuild, it won't work.  The BBLAYERS will be wrong unless you re-run:

    source meta-agl/scripts/aglsetup.sh -f  elisa-cluster-demo

or you edit build/conf/bblayers.conf and hand-add the changes.

I enabled nowayout on the watchdog.  This seems like the most prudent thing on a safety critical system.

You might want to add some information to the README.md about how to run the demo.  It took me a bit of time to figure it out, and I just kind of hacked something together that worked.  If we have a preferred way to run the demo, that would be very handy for users.

-corey

### CODE REVIEW

**Comment by sudipm-mukherjee** [comment]
@cminyard I did a fresh rebuild, and I can see in lsmod that `i6300esb` module is loaded. But on triggering the safe state the system does not reset. Do I need to add anything in the qemu argument to enable the watchdog?

**Comment by sudipm-mukherjee** [comment]
Ok, I checked and we will need to add `-watchdog i6300esb` to qemu commandline. And I can confirm it works properly.

**Comment by Jochen-Kall** [comment]
Hi Corey,

thanks for taking care of this, I'll give it a try tonight.

Good point you are making, the readme is a bit light on building instructions and running instructions with QEMU are missing entirely.
There were some in the document Jan-Simon provided, but they didn't make their way into the readme it seems.

We should also add the info that meta-elisa is an agl feature template now.

**Comment by Jochen-Kall** [comment]
Builds, runs and behaves as expected for me.

**Comment by cminyard** [comment]
On Thu, Mar 04, 2021 at 05:03:59AM -0800, Jochen Kall wrote:
> Builds, runs and behaves as expected for me.

Thanks for checking it out.  I should have mentioned enabling the
watchdog hardware emulator.

**Pull request merged**
