### PR TITLE
Add missing build step for "add-layer"

### PR DESCRIPTION
**Pull request by pahmann**
Add one missing step for adding the demo layer to the build

Signed-off-by: Philipp Ahmann <philipp.elisa.project@gmail.com>

### CODE REVIEW

**Comment by AGLExport** [comment]
Current layer design is supported agl feature by templates/feature/elisa-cluster-demo.
In this case, not need to "bitbake-layers add-layer".

Can you tell me in which environment (jj? master?) need it?

**Comment by Jochen-Kall** [comment]
I thought so too based on your commit messages, and the template, but when I tried to build, it did not work unless I manually add-layer it.
I'll give it a try once more in the evening and let you know what exactly it complains about if I don't add the layers by hand

**Comment by Jochen-Kall** [comment]
Gave it another try, whatever went wrong the first time around, a missing bitbake-layers add-layer was not the issue, it now builds just fine without it.
We can discard this pull request in my opinion, sorry for the confusion :P

**Comment by AGLExport** [comment]
Thank you Jochen.

I try to clean build yesterday.  In this timing, meta-elisa automagical include was available too.

**Comment by pahmann** [comment]
Thanks for clarification. It seems no action is required. I will close this PR.

**Pull request closed without merging**
