### PR TITLE
hello-world on meta-elisa layer with AGL demo

### PR DESCRIPTION
**Pull request by sudipm-mukherjee**
Changes include:
1) Add the earlier patch to show how to modify the cluster demo
2) Add a hello-world application.
3) Add a service file to start hello-world on boot.

Ref: https://lists.elisa.tech/g/automotive/message/88

### CODE REVIEW

**Comment by AGLExport** [comment]
1st step- Merge
Will change to new layer stricture.

**Comment by sudipm-mukherjee** [comment]
> 1st step- Merge
> Will change to new layer stricture.

Thanks @AGLExport. Will do. And at the same time I will remove the kernel update to v5.9.y which is not LTS.

**Comment by AGLExport** [comment]
@sudipm-mukherjee 
Thank you for your work.
I work to merge your contribute into upstream.  Current draft as a shown in https://github.com/AGLExport/meta-elisa.  Will delete kernel recipe in this repository.

**Comment by AGLExport** [comment]
Hi @sudipm-mukherjee 

I merged your work. Please check Pull request #4

**Comment by AGLExport** [comment]
This pull request include in #4.

**Pull request closed without merging**
