### PR TITLE
AGL base update from jellyfish to koi.

### PR DESCRIPTION
**Pull request by AGLExport**
AGL base update from jellyfish to koi.
I hope to review by contributors.

### CODE REVIEW

**Comment by AGLExport** [comment]
Hi @sudipm-mukherjee 
Thank you testing!

**Comment by Farshid-Monhaseri** [comment]
There is nothing wrong with this patch as I tested ... My build system is Ubuntu 20.04 x86_64, I built the image for the both jellyfish (current version) and also with this patch (koi) the results were equal.
Both of them fail to run the "vmdk" image with VirtualBox by default, because there are some specific setting to make enable the VirtualBox to boot the images with "EFI" mode. You can check those configs step by step [here](https://docs.automotivelinux.org/en/master/#0_Getting_Started/2_Building_AGL_Image/5_1_x86_Emulation_and_Hardware) on AGL documentations web page.


> Built this and the ext4 image works as expected. But for some reason the vmdk image did not work and was waiting to read from the floppy. But that I guess that should not matter as our README only says about using the ext4 image.
> 
> Thanks @AGLExport for working on this.

How do you exactly test (boot) the "vmdk" image?

**Comment by Farshid-Monhaseri** [comment]
I think these patch looks OK and If there are not another issue, It is good to be merged.

**Review by Farshid-Monhaseri — APPROVED** [review]

**Comment by Jochen-Kall** [comment]
I build it and ran it a couple times with QEMU, as far as I can tell everything works exactly as before.
A cosmetic, albeit hard to overlook issue presented itself though, in shape of a bright green square in the middle of the window:
Screenshot from 2021-06-25 06-53-50
I  checked against the last jellyfish build with identical QEMU settings to make sure it has nothing to do with that, and no green square there.

**Comment by pahmann** [comment]
The gree area is caused by an area which can be used by the IVI world to render additional information such as media player or navigation screen. Nothing to bother about. Reason for green color is most likely the initialization of the color format. You may see this sometimes in videos using YUV format.

**Pull request merged**
